plugins {
    id 'java'
}

group = 'com.camdaloon'
version = '1.0.0-7_beta'

repositories {
    maven { url = 'https://repo.papermc.io/repository/maven-public/' }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:1.21.11-R0.1-SNAPSHOT'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

processResources {
    filesMatching('plugin.yml') {
        expand(pluginVersion: project.version)
    }
}

jar {
    archiveBaseName = 'SimpleFlags'
}
