name: SimpleFlags
version: ${pluginVersion}
main: com.camdaloon.simpleflags.SimpleFlags
api-version: '1.21'
author: camdaloon
description: Adds in simple flags to Minecraft.
commands:
  simpleflags:
    description: Simple Flags command
    usage: /simpleflags reload
    aliases:
      - sf
