name: SimpleFlags
version: ${pluginVersion}
main: com.camdaloon.simpleflags.SimpleFlags
api-version: '1.21'
author: camdaloon
description: Adds in simple flags to Minecraft.
commands:
  simpleflags:
    description: Simple Flags command
    usage: /simpleflags <reload|name|upload>
    aliases:
      - sf
permissions:
  uploadflag:
    description: Allows use of the flag image upload feature
    default: op
