name: Simple Flags
version: ${pluginVersion}
main: com.camdaloon.simpleflags.SimpleFlags
description: Adds in simple flags to Minecraft.
author: camdaloon
api-version: '1.21.11'
commands:
  simpleflags:
    description: Simple Flags commands
    usage: /simpleflags reload
    aliases: [sflags]
permissions:
  simpleflags.admin:
    default: op
